class Commands:
    LEECH = "leech@ShreeScreenShotbot"
    PURGE = "purge@ShreeScreenShotbot"
    PAUSEALL = "pauseall@ShreeScreenShotbot"
    RESUMEALL = "resumeall@ShreeScreenShotbot"
    STATUS = "status@ShreeScreenShotbot"
    SETTINGS = "settings@ShreeScreenShotbot"
    EXEC = "exec@ShreeScreenShotbot"
    UPLOAD = "upload@ShreeScreenShotbot"
    YTDL = "ytdl@ShreeScreenShotbot"
    PYTDL = "pytdl@ShreeScreenShotbot"
    ABOUT = "about@ShreeScreenShotbot"
    GETLOGS = "getlogs@ShreeScreenShotbot"
    SERVER = "server@ShreeScreenShotbot"
    USERSETTINGS = "usetting@ShreeScreenShotbot"
    INSTADL = "instadl@ShreeScreenShotbot"
