class Commands:
    LEECH = "leech@ShreeLinkbot"
    PURGE = "purge@ShreeLinkbot"
    PAUSEALL = "pauseall@ShreeLinkbot"
    RESUMEALL = "resumeall@ShreeLinkbot"
    STATUS = "status@ShreeLinkbot"
    SETTINGS = "settings@ShreeLinkbot"
    EXEC = "exec@ShreeLinkbot"
    UPLOAD = "upload@ShreeLinkbot"
    YTDL = "ytdl@ShreeLinkbot"
    PYTDL = "pytdl@ShreeLinkbot"
    ABOUT = "about@ShreeLinkbot"
    GETLOGS = "getlogs@ShreeLinkbot"
    SERVER = "server@ShreeLinkbot"
    USERSETTINGS = "usetting@ShreeLinkbot"
    INSTADL = "instadl@ShreeLinkbot"
